%%% This file was automatically generated by snmpc_mib_to_hrl version 5.2.7
%%% Date: 25-Sep-2017::21:58:38
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
